[package]
name = "rust_thumbnails"
version = "0.1.1"
edition = "2021"

[lib]
name = "rust_thumbnails"
crate-type = ["cdylib"]

[dependencies]
exr = "1.74.0"
image = "0.25.9"
pyo3 = "0.27.2"
xcap = "0.7.1"

[profile.release]
lto = "fat"
opt-level = 3
