[package]
name = "rust_thumbnails"
version = "0.1.1"
edition = "2021"

[lib]
name = "rust_thumbnails"
crate-type = ["cdylib"]

[dependencies]
exr = "1.73.0"
image = "0.24.9"
pyo3 = "0.19.2"
xcap = "0.7.0"

[profile.release]
lto = "fat"
opt-level = 3
